owner: marchershey
repo: hersheynet-status

sites:
  - name: Production Server
    url: https://prod.hershey.co
  - name: Web Server
    url: https://web.hershey.co
  - name: NS1 (ns1.hershey.co)
    check: "tcp-ping"
    url: http://ns1.hershey.co
    port: 53
  - name: NS2 (ns2.hershey.co)
    check: "tcp-ping"
    url: http://ns2.hershey.co
    port: 53

status-website:
  cname: status.hershey.co
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HersheyNET
  introTitle: "This is the title"
  introMessage: This is the subtitle.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - marchershey

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
