owner: marchershey
repo: hersheynet-status

sites:
  - name: Production Server
    url: 45.32.212.135
  - name: Web Server
    url: https://web.hershey.co
  - name: NS1 (ns1.hershey.co)
    check: "tcp-ping"
    url: 155.138.230.28
    port: 53
  - name: NS2 (ns2.hershey.co)
    check: "tcp-ping"
    url: 45.32.223.202
    port: 53
  - name: Hershey Home
    url: https://home.hershey.co

status-website:
  cname: status.hershey.co
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HersheyNET
  introTitle: "This is the title"
  introMessage: This is the subtitle.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - marchershey
  
#workflowSchedule:
#  # init setup (runs everything) - runs daily at 03:00
#  updates: "0 3 * * *"
#  # update upptime - runs weekly on Sunday
#  updateTemplate: "0 0 * * 0"
#  # deploy status page - runs weekly on Sunday
#  staticSite: "0 0 * * 0"
#  # update README - runs hourly on min 2
#  summary: "2 * * * *"
#  # update graphs - runs hourly on min 1
#  graphs: "1 * * * *"
#  # log response time - runs hourly on min 0
#  responseTime: "0 * * * *"
#  # pings endpoints - runs every 5 mins
#  uptime: "*/5 * * * *"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# every 5 mins: "*/5 * * * *"
# every hour: "0 * * * *"
# every day: "0 1 * * *"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
