owner: marchershey
repo: hersheynet-status

sites:
  - name: Production Server
    url: 45.32.212.135
  - name: Web Server
    url: https://web.hershey.co
  - name: NS1 (ns1.hershey.co)
    check: "tcp-ping"
    url: 155.138.230.28
    port: 53
  - name: NS2 (ns2.hershey.co)
    check: "tcp-ping"
    url: 45.32.223.202
    port: 53
  - name: Hershey Home
    url: https://home.hershey.co

status-website:
  cname: status.hershey.co
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HersheyNET
  introTitle: "This is the title"
  introMessage: This is the subtitle.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - marchershey
  
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
